### ISSUE TITLE
create_comparelog() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by RonilPatel7** [Arthur-Milchior/anki-window-open-on-sync#1]
Seeing this error on 2.1.24

```
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-27 01:26:46

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\toolbar.py", line 154, in _linkHandler
  File "aqt\toolbar.py", line 178, in _syncLinkHandler
  File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\937448353\main.py", line 25, in onSync
    self._onSync()
  File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\937448353\main.py", line 33, in _onSync
    self._sync(action)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-92>", line 2, in _sync
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 632, in repl
TypeError: create_comparelog() takes 1 positional argument but 2 were given

```

**Comment by Arthur-Milchior** [comment]
I see you closed the bug report. is the problem gone ? 
When does it occur ?

**Comment by RonilPatel7** [comment]
This bug was seen originally on April 27, 2020; however it resolved after I downloaded the most recent version from ankiweb; no changes were necessary

**Comment by Arthur-Milchior** [comment]
Oh, my bad. I didn't realize that you just closed it but it was opened a long time ago. I usually try to answer quickly, so I thought I never considered it. I assume I may have answered you directly and forgot to put the information on github. Thank you for taking the time to close it
